displayName=Clan Clog
author=420 kc
support=https://github.com/420kc/clan-clog/issues
description=Search a clan, view its shared collection log
tags=clan,hiscores,420kc
plugins=com.clanclog.ClanClogPlugin
build=standard
